# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('build_no', models.CharField(max_length=8)),
                ('plan_suite', models.CharField(max_length=32)),
                ('module_testcase', models.CharField(max_length=128)),
                ('number_pass', models.IntegerField(default=0)),
                ('number_fail', models.IntegerField(default=0)),
                ('number_total', models.IntegerField(default=0)),
                ('number_passrate', models.DecimalField(decimal_places=2, default=100, max_digits=11)),
                ('unit', models.CharField(default='points', max_length=16)),
                ('measurement', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('lava_nick', models.CharField(default='', max_length=16)),
                ('job_id', models.CharField(default='', max_length=16)),
                ('job_name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('build_no', models.CharField(blank=True, default='', max_length=8)),
                ('build_no_fixed', models.CharField(blank=True, default='', max_length=8)),
                ('bug_id', models.CharField(max_length=16)),
                ('link', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('inprogress', 'InProgress'), ('resolved', 'Resolved')], max_length=64)),
                ('plan_suite', models.CharField(max_length=64)),
                ('module_testcase', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BuildBugzilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('new_bug_url', models.URLField()),
                ('product', models.CharField(max_length=64)),
                ('op_sys', models.CharField(max_length=32)),
                ('bug_severity', models.CharField(max_length=32)),
                ('component', models.CharField(max_length=64)),
                ('keywords', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('rep_platform', models.CharField(max_length=16)),
                ('short_desc_prefix', models.CharField(blank=True, default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BuildConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('img_ext', models.CharField(max_length=16)),
                ('base_build_name', models.CharField(max_length=64)),
                ('base_build_no', models.CharField(max_length=8)),
                ('template_dir', models.CharField(blank=True, default='', max_length=8)),
                ('bugzilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.BuildBugzilla')),
            ],
        ),
        migrations.CreateModel(
            name='BuildSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('build_no', models.CharField(max_length=8)),
                ('build_config', models.CharField(max_length=64)),
                ('build_commit', models.CharField(max_length=64)),
                ('android_version', models.CharField(max_length=32)),
                ('kernel_version', models.CharField(max_length=16)),
                ('kernel_url', models.CharField(max_length=256)),
                ('firmware_url', models.CharField(max_length=256)),
                ('firmware_version', models.CharField(max_length=64)),
                ('toolchain_info', models.CharField(max_length=256)),
                ('images_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('build_no', models.CharField(blank=True, default='', max_length=8)),
                ('build_no_fixed', models.CharField(blank=True, default='', max_length=8)),
                ('plan_suite', models.CharField(max_length=64)),
                ('module_testcase', models.CharField(max_length=128)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('build_no', models.CharField(max_length=8)),
                ('lava_nick', models.CharField(max_length=16)),
                ('job_id', models.CharField(max_length=16)),
                ('job_name', models.CharField(max_length=64)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Running'), (2, 'Complete'), (3, 'Incomplete'), (4, 'Canceled')])),
                ('duration', models.DurationField()),
                ('cached', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LAVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LAVAUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=128)),
                ('lava', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.LAVA')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=16)),
                ('measurement', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('unit', models.CharField(max_length=128, null=True)),
                ('suite', models.CharField(max_length=16)),
                ('job_id', models.CharField(max_length=16)),
                ('lava_nick', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='buildconfig',
            name='lava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.LAVA'),
        ),
    ]
