# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('build_no', models.CharField(max_length=8)),
                ('plan_suite', models.CharField(max_length=32)),
                ('module_testcase', models.CharField(max_length=128)),
                ('number_pass', models.IntegerField(default=0)),
                ('number_fail', models.IntegerField(default=0)),
                ('number_total', models.IntegerField(default=0)),
                ('number_passrate', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('unit', models.CharField(default='points', max_length=16)),
                ('measurement', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
            ],
        ),
    ]
