# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_baseresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('bug_id', models.CharField(max_length=16)),
                ('link', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('inprogress', 'InProgress'), ('resolved', 'Resolved')], max_length=64)),
                ('plan_suite', models.CharField(max_length=64)),
                ('module_testcase', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='testcase',
            name='measurement',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
