# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20171113_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('build_no', models.CharField(max_length=8)),
                ('build_config', models.CharField(max_length=64)),
                ('build_commit', models.CharField(max_length=64)),
                ('android_version', models.CharField(max_length=32)),
                ('kernel_version', models.CharField(max_length=16)),
                ('kernel_url', models.CharField(max_length=256)),
                ('firmware_url', models.CharField(max_length=256)),
                ('firmware_version', models.CharField(max_length=64)),
                ('toolchain_info', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('inprogress', 'InProgress'), ('resolved', 'Resolved')], max_length=64),
        ),
    ]
