# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-05 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180511_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsummary',
            name='cts_pkg_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='buildsummary',
            name='vts_pkg_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite',
            field=models.CharField(max_length=64),
        ),
    ]
