# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20171116_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsummary',
            name='images_url',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
