# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_buildsummary_images_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseresults',
            name='job_id',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='baseresults',
            name='job_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='baseresults',
            name='lava_nick',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='baseresults',
            name='number_passrate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=11),
        ),
    ]
