# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20171117_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresults',
            name='measurement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
