# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20171117_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAVAUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lava_nick', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=128)),
            ],
        ),
    ]
