# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_lavauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcache',
            name='build_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcache',
            name='build_no',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcache',
            name='duration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcache',
            name='job_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcache',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Running'), (2, 'Complete'), (3, 'Incomplete'), (4, 'Canceled')], default=0),
            preserve_default=False,
        ),
    ]
