# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20171120_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildBugzilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('new_bug_url', models.URLField()),
                ('product', models.CharField(max_length=64)),
                ('op_sys', models.CharField(max_length=32)),
                ('bug_severity', models.CharField(max_length=32)),
                ('component', models.CharField(max_length=64)),
                ('keywords', models.CharField(max_length=16)),
                ('rep_platform', models.CharField(max_length=16)),
                ('short_desc_prefix', models.CharField(max_length=16)),
            ],
        ),
    ]
