# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_buildbugzilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildbugzilla',
            name='keywords',
            field=models.CharField(default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='buildbugzilla',
            name='short_desc_prefix',
            field=models.CharField(default='', max_length=16),
        ),
    ]
