# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20171122_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('lava_nick', models.CharField(max_length=64)),
                ('img_ext', models.CharField(max_length=16)),
                ('base_build_name', models.CharField(max_length=64)),
                ('base_build_no', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='buildbugzilla',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='buildbugzilla',
            name='short_desc_prefix',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='buildconfig',
            name='bugzilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.BuildBugzilla'),
        ),
    ]
