# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20171122_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='buildconfig',
            name='lava_nick',
        ),
        migrations.RemoveField(
            model_name='lavauser',
            name='lava_nick',
        ),
        migrations.AddField(
            model_name='buildconfig',
            name='template_dir',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='buildconfig',
            name='lava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.LAVA'),
        ),
        migrations.AddField(
            model_name='lavauser',
            name='lava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.LAVA'),
        ),
    ]
