# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20171122_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=64)),
                ('build_no', models.CharField(blank=True, default='', max_length=8)),
                ('plan_suite', models.CharField(max_length=64)),
                ('module_testcase', models.CharField(max_length=128)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='build_no',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
