# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_bug_build_no_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcache',
            name='duration',
            field=models.DurationField(),
        ),
    ]
