# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20180116_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='build_no_fixed',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
