# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KernelChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=255)),
                ('reported', models.BooleanField()),
                ('trigger_name', models.CharField(max_length=255)),
                ('trigger_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cibuild',
            name='kernel_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkft.KernelChange'),
        ),
    ]
