# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0002_auto_20200221_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernelchange',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kernelchange',
            name='modules_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kernelchange',
            name='modules_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kernelchange',
            name='number_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kernelchange',
            name='number_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kernelchange',
            name='number_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kernelchange',
            name='result',
            field=models.CharField(default='NOINFO', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kernelchange',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cibuild',
            name='result',
            field=models.CharField(default='NOINFO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='modules_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='modules_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='number_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='number_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportbuild',
            name='number_total',
            field=models.IntegerField(default=0),
        ),
    ]
