# Generated by Django 3.0.3 on 2020-03-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0003_auto_20200225_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('project_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportbuild',
            name='group',
        ),
        migrations.RemoveField(
            model_name='reportbuild',
            name='name',
        ),
        migrations.AddField(
            model_name='reportbuild',
            name='qa_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lkft.ReportProject'),
        ),
    ]
