# Generated by Django 3.0.3 on 2020-03-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0004_auto_20200303_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportbuild',
            name='qa_build_id',
            field=models.IntegerField(default=0),
        ),
    ]
