# Generated by Django 3.0.3 on 2020-03-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0005_reportbuild_qa_build_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportbuild',
            name='status',
            field=models.CharField(default='NOINFO', max_length=100, null=True),
        ),
    ]
