# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-13 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0006_reportbuild_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cibuild',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='kernelchange',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
