# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0007_auto_20200413_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_url', models.CharField(max_length=100)),
                ('attachment_url', models.CharField(max_length=100, null=True)),
                ('qa_job_id', models.IntegerField(default=0)),
                ('parent_job', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='NOINFO', max_length=100, null=True)),
                ('failure_msg', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('fetched_at', models.DateTimeField(null=True)),
                ('number_passed', models.IntegerField(default=0)),
                ('number_failed', models.IntegerField(default=0)),
                ('number_total', models.IntegerField(default=0)),
                ('modules_done', models.IntegerField(default=0)),
                ('modules_total', models.IntegerField(default=0)),
                ('report_build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lkft.ReportBuild')),
            ],
        ),
    ]
