# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-22 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0008_reportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjob',
            name='resubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
