# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0009_reportjob_resubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='failure_msg',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
