# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0010_auto_20200623_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='attachment_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='job_url',
            field=models.URLField(null=True),
        ),
    ]
