# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0011_auto_20200623_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='failure_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
