# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0012_auto_20200623_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernelchange',
            name='jobs_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kernelchange',
            name='jobs_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportbuild',
            name='jobs_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportbuild',
            name='jobs_total',
            field=models.IntegerField(default=0),
        ),
    ]
